In [53]:
import pandas as pd

Crime = pd.read_csv('/Users/harryfranklin/Downloads/Crimes.csv')

Crime.head()

Battery = Crime[Crime['Primary Type'] == 'BATTERY']
Assault = Crime[Crime['Primary Type'] == 'ASSAULT']
SA = Crime[Crime['Primary Type'].isin(["CRIMINAL SEXUAL ASSAULT", "CRIM SEXUAL ASSAULT"])]
Homicide = Crime[Crime['Primary Type'] == 'HOMICIDE']

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

Crime.head(5)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14075483,JK105557,12/31/2025 11:58:00 PM,050XX S PAULINA ST,0560,ASSAULT,SIMPLE,RESIDENCE,False,False,931,9,20.0,61.0,08A,1165860.0,1871343.0,2025,01/09/2026 03:40:47 PM,41.802549,-87.667246,"(41.802549018, -87.667246428)"
1,14070845,JK100006,12/31/2025 11:54:00 PM,013XX W LAKE ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY",RESTAURANT,True,False,1215,12,27.0,28.0,08B,1167120.0,1901555.0,2025,01/08/2026 03:46:48 PM,41.885427,-87.661759,"(41.885426714, -87.661759042)"
2,14071367,JK100694,12/31/2025 11:50:00 PM,005XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,HOTEL / MOTEL,False,False,123,1,4.0,32.0,08B,1177364.0,1897937.0,2025,01/08/2026 03:46:48 PM,41.875273,-87.624251,"(41.875272573, -87.624251314)"
3,14070841,JK100162,12/31/2025 11:50:00 PM,068XX S PERRY AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,722,7,6.0,69.0,08B,1176577.0,1859676.0,2025,01/08/2026 03:46:48 PM,41.770299,-87.628294,"(41.77029895, -87.628293582)"
4,14070846,JK100015,12/31/2025 11:47:00 PM,004XX W SURF ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,1934,19,44.0,6.0,08B,1172790.0,1919420.0,2025,01/08/2026 03:46:48 PM,41.934326,-87.640408,"(41.934325528, -87.640407923)"

In [29]:
import geopandas as gpd
from shapely.geometry import Point

tracts = gpd.read_file("/Users/harryfranklin/Downloads/Census_20Tracts/Census_Tracts.shp")

geometry = [
    Point(xy) for xy in zip(Crime["Longitude"], Crime["Latitude"])
]

crimes_gdf = gpd.GeoDataFrame(
    Crime,
    geometry=geometry,
    crs="EPSG:4326"  
)

tracts = tracts.to_crs(crimes_gdf.crs)

crimes_with_tracts = gpd.sjoin(
    crimes_gdf,
    tracts,
    how="left",
    predicate="within"
)

crimes_with_tracts

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,geometry,index_right,OBJECTID,CENSUS_TRA,CENSUS_T_1,TRACT_FIPS,TRACT_CENT,TRACT_CE_1,TRACT_CE_2,TRACT_CE_3,TRACT_COMM,TRACT_NUMA,TRACT_CENS,PERIMETER,DATA_ADMIN,TRACT_CREA,TRACT_CR_1,SHAPE_AREA,SHAPE_LEN
0,14075483,JK105557,12/31/2025 11:58:00 PM,050XX S PAULINA ST,0560,ASSAULT,SIMPLE,RESIDENCE,False,False,931,9,20.0,61.0,08A,1165860.0,1871343.0,2025,01/09/2026 03:40:47 PM,41.802549,-87.667246,"(41.802549018, -87.667246428)",POINT (-87.66725 41.80255),361.0,362.0,611300,17031611300,17031,1.165837e+06,1.872213e+06,-87.667304,41.804936,61,20.0,2000.0,0.0,0.0,None,NaT,3.519757e+06,7961.120187
1,14070845,JK100006,12/31/2025 11:54:00 PM,013XX W LAKE ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY",RESTAURANT,True,False,1215,12,27.0,28.0,08B,1167120.0,1901555.0,2025,01/08/2026 03:46:48 PM,41.885427,-87.661759,"(41.885426714, -87.661759042)",POINT (-87.66176 41.88543),266.0,267.0,280300,17031280300,17031,1.167090e+06,1.901479e+06,-87.661873,41.885218,28,44.0,2000.0,0.0,0.0,None,NaT,7.416175e+06,10889.387157
2,14071367,JK100694,12/31/2025 11:50:00 PM,005XX S MICHIGAN AVE,0460,BATTERY,SIMPLE,HOTEL / MOTEL,False,False,123,1,4.0,32.0,08B,1177364.0,1897937.0,2025,01/08/2026 03:46:48 PM,41.875273,-87.624251,"(41.875272573, -87.624251314)",POINT (-87.62425 41.87527),558.0,559.0,320400,17031320400,17031,1.179223e+06,1.898847e+06,-87.617400,41.877728,32,29.0,2000.0,0.0,0.0,None,NaT,1.564957e+07,19162.046208
3,14070841,JK100162,12/31/2025 11:50:00 PM,068XX S PERRY AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,722,7,6.0,69.0,08B,1176577.0,1859676.0,2025,01/08/2026 03:46:48 PM,41.770299,-87.628294,"(41.77029895, -87.628293582)",POINT (-87.62829 41.7703),746.0,747.0,690300,17031690300,17031,1.176394e+06,1.859080e+06,-87.628983,41.768667,69,32.0,2000.0,0.0,0.0,None,NaT,5.551874e+06,10503.727971
4,14070846,JK100015,12/31/2025 11:47:00 PM,004XX W SURF ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,1934,19,44.0,6.0,08B,1172790.0,1919420.0,2025,01/08/2026 03:46:48 PM,41.934326,-87.640408,"(41.934325528, -87.640407923)",POINT (-87.64041 41.93433),707.0,708.0,063300,17031063300,17031,1.173497e+06,1.919547e+06,-87.637808,41.934658,6,15.0,2000.0,0.0,0.0,None,NaT,4.831993e+06,10647.976128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334521,12258861,JE100369,01/01/2021 12:00:00 AM,016XX N CICERO AVE,051A,ASSAULT,AGGRAVATED - HANDGUN,ALLEY,False,False,2533,25,37.0,25.0,04A,1144145.0,1910673.0,2021,01/16/2021 03:39:23 PM,41.910910,-87.745899,"(41.910909931, -87.745898897)",POINT (-87.7459 41.91091),649.0,650.0,250200,17031250200,17031,1.142734e+06,1.911164e+06,-87.751070,41.912285,25,18.0,2000.0,0.0,0.0,None,NaT,5.244786e+06,9287.344867
334522,12259383,JE100487,01/01/2021 12:00:00 AM,112XX S HALSTED ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,2233,22,34.0,49.0,08B,1172995.0,1830233.0,2021,01/16/2021 03:39:23 PM,41.689583,-87.642290,"(41.689583135, -87.64229016)",POINT (-87.64229 41.68958),249.0,250.0,750600,17031750600,17031,1.170332e+06,1.829865e+06,-87.652049,41.688632,75,64.0,2000.0,0.0,0.0,None,NaT,1.416884e+07,16651.093717
334523,12307445,JE159529,01/01/2021 12:00:00 AM,035XX W MONROE ST,0265,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - OTHER,OTHER (SPECIFY),False,False,1123,11,28.0,27.0,02,1152721.0,1899304.0,2021,03/09/2021 03:39:45 PM,41.879547,-87.714695,"(41.879546781, -87.714694612)",POINT (-87.71469 41.87955),728.0,729.0,271400,17031271400,17031,1.153098e+06,1.898467e+06,-87.713331,41.877244,27,16.0,2000.0,0.0,0.0,None,NaT,3.534613e+06,7973.054528
334524,12258747,JE100294,01/01/2021 12:00:00 AM,123XX S HALSTED ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,STREET,False,True,523,5,34.0,53.0,08B,1173227.0,1823129.0,2021,01/16/2021 03:39:23 PM,41.670084,-87.641650,"(41.670083502, -87.641649599)",POINT (-87.64165 41.67008),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
334525,12319911,JE174516,01/01/2021 12:00:00 AM,024XX W 66TH ST,0266,CRIMINAL SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,False,832,8,16.0,66.0,02,1161324.0,1860827.0,2021,03/23/2021 03:39:32 PM,41.773787,-87.684173,"(41.773786968, -87.684173165)",POINT (-87.68417 41.77379),464.0,465.0,660800,17031660800,17031,1.158844e+06,1.860755e+06,-87.693265,41.773641,66,32.0,2000.0,0.0,0.0,None,NaT,7.053372e+06,13306.438389

In [55]:
Crime = crimes_with_tracts.iloc[:, :-14]
Crime["Date"] = pd.to_datetime(Crime["Date"])

Battery = Crime[Crime['Primary Type'] == 'BATTERY']
Assault = Crime[Crime['Primary Type'] == 'ASSAULT']
SA = Crime[Crime['Primary Type'].isin(["CRIMINAL SEXUAL ASSAULT", "CRIM SEXUAL ASSAULT"])]
Homicide = Crime[Crime['Primary Type'] == 'HOMICIDE']
DV = Crime[Crime['Primary Type'] == 'DOMESTIC VIOLENCE']

Assault

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/1504322734.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Crime["Date"] = pd.to_datetime(Crime["Date"])

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,geometry,index_right,OBJECTID,CENSUS_TRA,CENSUS_T_1
0,14075483,JK105557,2025-12-31 23:58:00,050XX S PAULINA ST,0560,ASSAULT,SIMPLE,RESIDENCE,False,False,931,9,20.0,61.0,08A,1165860.0,1871343.0,2025,01/09/2026 03:40:47 PM,41.802549,-87.667246,"(41.802549018, -87.667246428)",POINT (-87.66725 41.80255),361.0,362.0,611300,17031611300
10,14070821,JK100040,2025-12-31 23:30:00,051XX S CALUMET AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,231,2,3.0,40.0,08A,1179365.0,1870976.0,2025,01/08/2026 03:46:48 PM,41.801244,-87.617729,"(41.801244072, -87.617729246)",POINT (-87.61773 41.80124),527.0,528.0,400100,17031400100
12,14070751,JJ540658,2025-12-31 23:06:00,006XX N CENTRAL PARK AVE,051A,ASSAULT,AGGRAVATED - HANDGUN,RESIDENCE - PORCH / HALLWAY,False,False,1121,11,27.0,23.0,04A,1152269.0,1904032.0,2025,01/08/2026 03:46:48 PM,41.892530,-87.716229,"(41.892529831, -87.716229454)",POINT (-87.71623 41.89253),864.0,865.0,231500,17031231500
15,14070808,JJ540673,2025-12-31 22:57:00,028XX W ARTHINGTON ST,051A,ASSAULT,AGGRAVATED - HANDGUN,APARTMENT,True,True,1135,11,28.0,27.0,04A,1157473.0,1895911.0,2025,01/08/2026 03:46:48 PM,41.870141,-87.697338,"(41.870140733, -87.697338234)",POINT (-87.69734 41.87014),379.0,380.0,271800,17031271800
16,14070770,JJ540651,2025-12-31 22:45:00,025XX W GUNNISON ST,0560,ASSAULT,SIMPLE,APARTMENT,False,True,2031,20,40.0,4.0,08A,1158564.0,1932193.0,2025,01/08/2026 03:46:48 PM,41.969679,-87.692337,"(41.969679008, -87.692337191)",POINT (-87.69234 41.96968),212.0,213.0,040200,17031040200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334467,12258986,JE100548,2021-01-01 01:32:00,038XX W FILLMORE ST,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1133,11,24.0,29.0,08A,1151043.0,1895100.0,2021,11/17/2021 03:40:16 PM,41.868044,-87.720966,"(41.868043561, -87.720966147)",POINT (-87.72097 41.86804),626.0,627.0,290700,17031290700
334472,12258648,JE100098,2021-01-01 01:22:00,009XX W 63RD PKWY,0560,ASSAULT,SIMPLE,APARTMENT,False,False,712,7,16.0,68.0,08A,1171301.0,1863652.0,2021,01/16/2021 03:39:23 PM,41.781327,-87.647517,"(41.781326622, -87.647516964)",POINT (-87.64752 41.78133),431.0,432.0,680700,17031680700
334474,12259387,JE100026,2021-01-01 01:00:00,001XX W 63RD ST,0560,ASSAULT,SIMPLE,GAS STATION,False,False,311,3,20.0,68.0,08A,1176275.0,1863208.0,2021,01/16/2021 03:39:23 PM,41.779998,-87.629295,"(41.77999793, -87.629294594)",POINT (-87.62929 41.78),748.0,749.0,680100,17031680100
334520,12317576,JE171603,2021-01-01 00:00:00,025XX S CALIFORNIA AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,True,1034,10,24.0,30.0,08A,1158104.0,1887202.0,2021,03/19/2021 03:39:40 PM,41.846229,-87.695259,"(41.846229464, -87.695259244)",POINT (-87.69526 41.84623),726.0,727.0,301100,17031301100
334521,12258861,JE100369,2021-01-01 00:00:00,016XX N CICERO AVE,051A,ASSAULT,AGGRAVATED - HANDGUN,ALLEY,False,False,2533,25,37.0,25.0,04A,1144145.0,1910673.0,2021,01/16/2021 03:39:23 PM,41.910910,-87.745899,"(41.910909931, -87.745898897)",POINT (-87.7459 41.91091),649.0,650.0,250200,17031250200

In [46]:
import altair as alt
alt.data_transformers.disable_max_rows()
monthly = (
    Battery
    .groupby(pd.Grouper(key="Date", freq="M"))
    .size()
    .reset_index(name="monthly_count")
)

chart = (
    alt.Chart(monthly)
    .mark_line(point=True)
    .encode(
        x=alt.X(
            "Date:T",
            title="Month"
        ),
        y=alt.Y(
            "monthly_count:Q",
            title="Number of Battery Crimes"
        ),
        tooltip=[
            alt.Tooltip("Date:T", title="Month"),
            alt.Tooltip("monthly_count:Q", title="Count")
        ]
    )
    .properties(
        title="Reported Battery Crimes by Month (2021–2025)",
        width=700,
        height=400
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/803723158.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .groupby(pd.Grouper(key="Date", freq="M"))

alt.Chart(...)

In [47]:
monthly = (
    Homicide
    .groupby(pd.Grouper(key="Date", freq="M"))
    .size()
    .reset_index(name="monthly_count")
)

chart = (
    alt.Chart(monthly)
    .mark_line(point=True)
    .encode(
        x=alt.X(
            "Date:T",
            title="Month"
        ),
        y=alt.Y(
            "monthly_count:Q",
            title="Number of Homicide Crimes"
        ),
        tooltip=[
            alt.Tooltip("Date:T", title="Month"),
            alt.Tooltip("monthly_count:Q", title="Count")
        ]
    )
    .properties(
        title="Reported Homicide Crimes by Month (2021–2025)",
        width=700,
        height=400
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/943777799.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .groupby(pd.Grouper(key="Date", freq="M"))

alt.Chart(...)

In [50]:
monthly = (
    SA
    .groupby(pd.Grouper(key="Date", freq="M"))
    .size()
    .reset_index(name="monthly_count")
)

chart = (
    alt.Chart(monthly)
    .mark_line(point=True)
    .encode(
        x=alt.X(
            "Date:T",
            title="Month"
        ),
        y=alt.Y(
            "monthly_count:Q",
            title="Number of Sexual Assault Crimes"
        ),
        tooltip=[
            alt.Tooltip("Date:T", title="Month"),
            alt.Tooltip("monthly_count:Q", title="Count")
        ]
    )
    .properties(
        title="Reported Sexual Assault Crimes by Month (2021–2025)",
        width=700,
        height=400
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/3527377920.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .groupby(pd.Grouper(key="Date", freq="M"))

alt.Chart(...)

In [51]:
monthly = (
    Assault
    .groupby(pd.Grouper(key="Date", freq="M"))
    .size()
    .reset_index(name="monthly_count")
)

chart = (
    alt.Chart(monthly)
    .mark_line(point=True)
    .encode(
        x=alt.X(
            "Date:T",
            title="Month"
        ),
        y=alt.Y(
            "monthly_count:Q",
            title="Number of Assault Crimes"
        ),
        tooltip=[
            alt.Tooltip("Date:T", title="Month"),
            alt.Tooltip("monthly_count:Q", title="Count")
        ]
    )
    .properties(
        title="Reported Assault Crimes by Month (2021–2025)",
        width=700,
        height=400
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/2700711255.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .groupby(pd.Grouper(key="Date", freq="M"))

alt.Chart(...)

In [67]:
Assault["Date"] = pd.to_datetime(Assault["Date"])

if "quintile" in Assault.columns:
    Assault = Assault.drop(columns=["quintile"])

tract_counts = (
    Assault
    .groupby("CENSUS_T_1")
    .size()
    .reset_index(name="total_assaults")
)

tract_counts["quintile"] = pd.qcut(
    tract_counts["total_assaults"],
    5,
    labels=["Q1 (Lowest)", "Q2", "Q3", "Q4", "Q5 (Highest)"]
)

Assault = Assault.merge(
    tract_counts[["CENSUS_T_1", "quintile"]],
    on="CENSUS_T_1",
    how="left"
)

Assault["month"] = Assault["Date"].dt.to_period("M").dt.to_timestamp()

quintile_time = (
    Assault
    .groupby(["month", "quintile"])
    .size()
    .reset_index(name="assault_count")
)

chart = (
    alt.Chart(quintile_time)
    .mark_line()
    .encode(
        x=alt.X("month:T", title="Month"),
        y=alt.Y("assault_count:Q", title="Number of Assaults"),
        color=alt.Color("quintile:N", title="Census Tract Quintile"),
    )
    .properties(
        width=700,
        height=400,
        title="Monthly Assaults by Census Tract Quintile"
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/821424566.py:29: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["month", "quintile"])

alt.Chart(...)

In [68]:
Battery["Date"] = pd.to_datetime(Battery["Date"])

if "quintile" in Battery.columns:
    Battery = Battery.drop(columns=["quintile"])

tract_counts = (
    Battery
    .groupby("CENSUS_T_1")
    .size()
    .reset_index(name="total_batteries")
)

tract_counts["quintile"] = pd.qcut(
    tract_counts["total_batteries"],
    5,
    labels=["Q1 (Lowest)", "Q2", "Q3", "Q4", "Q5 (Highest)"]
)

Battery = Battery.merge(
    tract_counts[["CENSUS_T_1", "quintile"]],
    on="CENSUS_T_1",
    how="left"
)

Battery["month"] = Battery["Date"].dt.to_period("M").dt.to_timestamp()

quintile_time = (
    Battery
    .groupby(["month", "quintile"])
    .size()
    .reset_index(name="battery_count")
)

chart = (
    alt.Chart(quintile_time)
    .mark_line()
    .encode(
        x=alt.X("month:T", title="Month"),
        y=alt.Y("battery_count:Q", title="Number of Batteries"),
        color=alt.Color("quintile:N", title="Census Tract Quintile"),
    )
    .properties(
        width=700,
        height=400,
        title="Monthly Batteries by Census Tract Quintile"
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/149124489.py:29: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["month", "quintile"])

alt.Chart(...)

In [69]:
SA["Date"] = pd.to_datetime(SA["Date"])

if "quintile" in SA.columns:
    SA = SA.drop(columns=["quintile"])

tract_counts = (
    SA
    .groupby("CENSUS_T_1")
    .size()
    .reset_index(name="total_sexual_assaults")
)

tract_counts["quintile"] = pd.qcut(
    tract_counts["total_sexual_assaults"],
    5,
    labels=["Q1 (Lowest)", "Q2", "Q3", "Q4", "Q5 (Highest)"]
)

SA = SA.merge(
    tract_counts[["CENSUS_T_1", "quintile"]],
    on="CENSUS_T_1",
    how="left"
)

SA["month"] = SA["Date"].dt.to_period("M").dt.to_timestamp()

quintile_time = (
    SA
    .groupby(["month", "quintile"])
    .size()
    .reset_index(name="sexual_assault_count")
)

chart = (
    alt.Chart(quintile_time)
    .mark_line()
    .encode(
        x=alt.X("month:T", title="Month"),
        y=alt.Y("sexual_assault_count:Q", title="Number of Sexual Assaults"),
        color=alt.Color("quintile:N", title="Census Tract Quintile"),
    )
    .properties(
        width=700,
        height=400,
        title="Monthly Sexual Assaults by Census Tract Quintile"
    )
)

chart

/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/3892814886.py:29: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["month", "quintile"])

alt.Chart(...)

In [72]:
Homicide["Date"] = pd.to_datetime(Homicide["Date"])

if "quintile" in Homicide.columns:
    Homicide = Homicide.drop(columns=["quintile"])

tract_counts = tract_counts.sort_values("total_homicides")

tract_counts["quintile"] = pd.qcut(
    tract_counts["total_homicides"].rank(method="first"),
    5,
    labels=["Q1 (Lowest)", "Q2", "Q3", "Q4", "Q5 (Highest)"]
)

Homicide = Homicide.merge(
    tract_counts[["CENSUS_T_1", "quintile"]],
    on="CENSUS_T_1",
    how="left"
)

Homicide["month"] = Homicide["Date"].dt.to_period("M").dt.to_timestamp()

quintile_time = (
    Homicide
    .groupby(["month", "quintile"])
    .size()
    .reset_index(name="homicide_count")
)

chart = (
    alt.Chart(quintile_time)
    .mark_line()
    .encode(
        x=alt.X("month:T", title="Month"),
        y=alt.Y("homicide_count:Q", title="Number of Homicides"),
        color=alt.Color("quintile:N", title="Census Tract Quintile"),
    )
    .properties(
        width=700,
        height=400,
        title="Monthly Homicides by Census Tract Quintile"
    )
)

chart

/opt/homebrew/Caskroom/miniconda/base/envs/dap/lib/python3.12/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/var/folders/b5/sqkbx53x2j1dprnygsh7sqn40000gn/T/ipykernel_46023/1321756351.py:24: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["month", "quintile"])

alt.Chart(...)

In [96]:
Crime["Primary Type"] = Crime["Primary Type"].replace(
    ["CRIM SEXUAL ASSAULT", "CRIMINAL SEXUAL ASSAULT"],
    "SEXUAL ASSAULT"
)
Crime["Date"] = pd.to_datetime(Crime["Date"])
Crime2023 = Crime[Crime["Date"].dt.year == 2023].copy()
Crime2023

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,geometry,index_right,OBJECTID,CENSUS_TRA,CENSUS_T_1
138016,13324997,JH100010,2023-12-31 23:51:00,009XX E 77TH ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,624,6,8.0,69.0,04A,1183685.0,1854148.0,2023,12/21/2024 03:40:46 PM,41.754967,-87.602411,"(41.754966726, -87.602410989)",POINT (-87.60241 41.75497),314.0,315.0,691500,17031691500
138017,13325009,JH100002,2023-12-31 23:51:00,051XX S PRINCETON AVE,0550,ASSAULT,AGGRAVATED POLICE OFFICER - HANDGUN,STREET,True,False,935,9,20.0,37.0,04A,1175152.0,1871065.0,2023,12/21/2024 03:40:46 PM,41.801584,-87.633177,"(41.801583507, -87.633177068)",POINT (-87.63318 41.80158),77.0,78.0,370400,17031370400
138018,13324829,JG561343,2023-12-31 23:50:00,014XX N LOCKWOOD AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY",STREET,False,False,2532,25,37.0,25.0,08B,1140764.0,1909050.0,2023,12/21/2024 03:40:46 PM,41.906519,-87.758360,"(41.906519104, -87.758359629)",POINT (-87.75836 41.90652),287.0,288.0,250700,17031250700
138019,13324881,JH100006,2023-12-31 23:50:00,051XX S WASHTENAW AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,923,9,14.0,63.0,08B,1159244.0,1870437.0,2023,12/21/2024 03:40:46 PM,41.800201,-87.691535,"(41.800200965, -87.691535096)",POINT (-87.69154 41.8002),29.0,30.0,630500,17031630500
138020,13324845,JH100031,2023-12-31 23:45:00,016XX W WALNUT ST,0460,BATTERY,SIMPLE,OTHER (SPECIFY),False,False,1215,12,27.0,28.0,08B,1165374.0,1901800.0,2023,12/21/2024 03:40:46 PM,41.886136,-87.668164,"(41.886136329, -87.668163684)",POINT (-87.66816 41.88614),801.0,802.0,280400,17031280400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207212,14053080,JJ519112,2023-01-01 00:00:00,045XX S CALIFORNIA AVE,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,922,9,12.0,58.0,04A,NaN,NaN,2023,12/12/2025 03:42:39 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,NaN
207213,13422824,JH217572,2023-01-01 00:00:00,027XX W GIDDINGS ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,1911,19,40.0,4.0,04A,NaN,NaN,2023,04/09/2024 03:42:08 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,NaN
207214,13314916,JG549655,2023-01-01 00:00:00,041XX N BROADWAY,0265,SEXUAL ASSAULT,AGGRAVATED - OTHER,RESIDENCE,False,False,1915,19,46.0,3.0,02,1169367.0,1928016.0,2023,12/24/2023 03:41:06 PM,41.957989,-87.652736,"(41.957988526, -87.652736487)",POINT (-87.65274 41.95799),227.0,228.0,032100,17031032100
207215,13382135,JH168263,2023-01-01 00:00:00,077XX S CREGIER AVE,0281,SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,False,414,4,8.0,43.0,02,NaN,NaN,2023,02/28/2024 03:41:06 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,NaN
207216,12938772,JG100243,2023-01-01 00:00:00,073XX S ABERDEEN ST,0266,SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,False,733,7,17.0,68.0,02,1170254.0,1856107.0,2023,02/09/2024 03:40:56 PM,41.760645,-87.651575,"(41.760645062, -87.651574764)",POINT (-87.65157 41.76065),10.0,11.0,681400,17031681400

In [97]:
PMH2023 = pd.read_csv("/Users/harryfranklin/Downloads/PMH2023.csv")
Crime2023["CENSUS_T_1"] = Crime2023["CENSUS_T_1"].astype(str)
PMH2023["GEOID"] = PMH2023["GEOID"].astype(str)
Crime2023 = Crime2023.merge(
    PMH2023[["GEOID", "PMH_2023"]],
    left_on="CENSUS_T_1",
    right_on="GEOID",
    how="left"
)

Crime2023 = Crime2023.drop(
    columns=[col for col in Crime2023.columns if "GEOID" in col],
    errors="ignore"
)

SES2023 = pd.read_csv("/Users/harryfranklin/Downloads/SES2023.csv")
Crime2023["CENSUS_T_1"] = Crime2023["CENSUS_T_1"].astype(str)
SES2023["GEOID"] = SES2023["GEOID"].astype(str)
Crime2023 = Crime2023.merge(
    SES2023[["GEOID", "SES_2023"]],
    left_on="CENSUS_T_1",
    right_on="GEOID",
    how="left"
)

Crime2023 = Crime2023.drop(
    columns=[col for col in Crime2023.columns if "GEOID" in col],
    errors="ignore"
)

HI2023 = pd.read_csv("/Users/harryfranklin/Downloads/HI2023.csv")
Crime2023["CENSUS_T_1"] = Crime2023["CENSUS_T_1"].astype(str)
HI2023["GEOID"] = HI2023["GEOID"].astype(str)
Crime2023 = Crime2023.merge(
    HI2023[["GEOID", "HDX_2019-2023"]],
    left_on="CENSUS_T_1",
    right_on="GEOID",
    how="left"
)

Crime2023 = Crime2023.drop(
    columns=[col for col in Crime2023.columns if "GEOID" in col],
    errors="ignore"
)

CHI2023 = pd.read_csv("/Users/harryfranklin/Downloads/CHI2023.csv")
Crime2023["CENSUS_T_1"] = Crime2023["CENSUS_T_1"].astype(str)
CHI2023["GEOID"] = CHI2023["GEOID"].astype(str)
Crime2023 = Crime2023.merge(
    CHI2023[["GEOID", "CHACFZN_2023"]],
    left_on="CENSUS_T_1",
    right_on="GEOID",
    how="left"
)

Crime2023 = Crime2023.drop(
    columns=[col for col in Crime2023.columns if "GEOID" in col],
    errors="ignore"
)

Crime2023

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,geometry,index_right,OBJECTID,CENSUS_TRA,CENSUS_T_1,PMH_2023,SES_2023,HDX_2019-2023,CHACFZN_2023
0,13324997,JH100010,2023-12-31 23:51:00,009XX E 77TH ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,624,6,8.0,69.0,04A,1183685.0,1854148.0,2023,12/21/2024 03:40:46 PM,41.754967,-87.602411,"(41.754966726, -87.602410989)",POINT (-87.60241 41.75497),314.0,315.0,691500,17031691500,21.3,36.9,97.7,8.0
1,13325009,JH100002,2023-12-31 23:51:00,051XX S PRINCETON AVE,0550,ASSAULT,AGGRAVATED POLICE OFFICER - HANDGUN,STREET,True,False,935,9,20.0,37.0,04A,1175152.0,1871065.0,2023,12/21/2024 03:40:46 PM,41.801584,-87.633177,"(41.801583507, -87.633177068)",POINT (-87.63318 41.80158),77.0,78.0,370400,17031370400,NaN,NaN,NaN,NaN
2,13324829,JG561343,2023-12-31 23:50:00,014XX N LOCKWOOD AVE,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY",STREET,False,False,2532,25,37.0,25.0,08B,1140764.0,1909050.0,2023,12/21/2024 03:40:46 PM,41.906519,-87.758360,"(41.906519104, -87.758359629)",POINT (-87.75836 41.90652),287.0,288.0,250700,17031250700,19.9,37.6,92.5,3.0
3,13324881,JH100006,2023-12-31 23:50:00,051XX S WASHTENAW AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,923,9,14.0,63.0,08B,1159244.0,1870437.0,2023,12/21/2024 03:40:46 PM,41.800201,-87.691535,"(41.800200965, -87.691535096)",POINT (-87.69154 41.8002),29.0,30.0,630500,17031630500,16.9,31.4,92.4,10.0
4,13324845,JH100031,2023-12-31 23:45:00,016XX W WALNUT ST,0460,BATTERY,SIMPLE,OTHER (SPECIFY),False,False,1215,12,27.0,28.0,08B,1165374.0,1901800.0,2023,12/21/2024 03:40:46 PM,41.886136,-87.668164,"(41.886136329, -87.668163684)",POINT (-87.66816 41.88614),801.0,802.0,280400,17031280400,20.4,35.5,74.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,14053080,JJ519112,2023-01-01 00:00:00,045XX S CALIFORNIA AVE,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,922,9,12.0,58.0,04A,NaN,NaN,2023,12/12/2025 03:42:39 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN
69197,13422824,JH217572,2023-01-01 00:00:00,027XX W GIDDINGS ST,0530,ASSAULT,AGGRAVATED - OTHER DANGEROUS WEAPON,APARTMENT,False,True,1911,19,40.0,4.0,04A,NaN,NaN,2023,04/09/2024 03:42:08 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN
69198,13314916,JG549655,2023-01-01 00:00:00,041XX N BROADWAY,0265,SEXUAL ASSAULT,AGGRAVATED - OTHER,RESIDENCE,False,False,1915,19,46.0,3.0,02,1169367.0,1928016.0,2023,12/24/2023 03:41:06 PM,41.957989,-87.652736,"(41.957988526, -87.652736487)",POINT (-87.65274 41.95799),227.0,228.0,032100,17031032100,16.0,25.0,46.6,44.0
69199,13382135,JH168263,2023-01-01 00:00:00,077XX S CREGIER AVE,0281,SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,False,414,4,8.0,43.0,02,NaN,NaN,2023,02/28/2024 03:41:06 PM,NaN,NaN,NaN,POINT EMPTY,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN
69200,12938772,JG100243,2023-01-01 00:00:00,073XX S ABERDEEN ST,0266,SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,False,733,7,17.0,68.0,02,1170254.0,1856107.0,2023,02/09/2024 03:40:56 PM,41.760645,-87.651575,"(41.760645062, -87.651574764)",POINT (-87.65157 41.76065),10.0,11.0,681400,17031681400,19.4,36.7,69.7,5.0

In [99]:
Crime2023 = Crime2023.rename(columns={"HDX_2019-2023": "HDX"})
Crime2023 = Crime2023.rename(columns={"CHACFZN_2023": "COI"})